# Generated by Django 4.2.7 on 2025-08-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_serials_started', models.PositiveIntegerField(default=0)),
                ('total_serials_completed', models.PositiveIntegerField(default=0)),
                ('total_defects_found', models.PositiveIntegerField(default=0)),
                ('total_scrapped', models.PositiveIntegerField(default=0)),
                ('first_pass_yield_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de números de serie que pasaron sin defectos', max_digits=5)),
                ('average_cycle_time_minutes', models.DecimalField(decimal_places=2, default=0.0, help_text='Tiempo promedio de ciclo en minutos', max_digits=8)),
                ('defect_rate_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de defectos encontrados', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Producción',
                'verbose_name_plural': 'Métricas de Producción',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('DELAY', 'Retraso en Producción'), ('QUALITY', 'Problema de Calidad'), ('MAINTENANCE', 'Mantenimiento Requerido'), ('INVENTORY', 'Problema de Inventario'), ('GENERAL', 'Alerta General')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serials.serialnumber')),
            ],
            options={
                'verbose_name': 'Alerta de Producción',
                'verbose_name_plural': 'Alertas de Producción',
                'ordering': ['-created_at'],
            },
        ),
    ]
