# Generated by Django 4.2.7 on 2025-08-15 16:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Número de parte autorizado', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Descripción del componente')),
                ('revision', models.CharField(default='A', help_text='Revisión actual del componente', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el componente está activo para uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Componente Autorizado',
                'verbose_name_plural': 'Componentes Autorizados',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Formato: KM###W###R', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El número de serie debe tener el formato KM###W###R', regex='^KM\\d{3}W\\d{3}R$')])),
                ('order_number', models.CharField(help_text='Número de orden asociado', max_length=50)),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('IN_PROCESS', 'En Proceso'), ('COMPLETED', 'Completado'), ('REJECTED', 'Rechazado'), ('DEFECTIVE', 'Con Defecto'), ('SCRAPPED', 'Desechado')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_part', models.ForeignKey(help_text='Componente autorizado asociado', on_delete=django.db.models.deletion.PROTECT, to='serials.authorizedpart')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_serials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Número de Serie',
                'verbose_name_plural': 'Números de Serie',
                'ordering': ['-created_at'],
            },
        ),
    ]
