# Generated by Django 4.2.7 on 2025-08-18 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_add_sku_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='serial_number',
            field=models.CharField(help_text='Formato: [AÑO][MES]###-###M (ej: KA001-001M para enero 2025)', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El número de serie debe tener el formato [AÑO][MES]###-###M (ej: KA001-001M)', regex='^[K-Z][A-L]\\d{3}-\\d{3}M$')]),
        ),
    ]
