# Generated by Django 4.2.7 on 2025-08-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la operación', max_length=100)),
                ('description', models.TextField(help_text='Descripción detallada de la operación')),
                ('sequence_number', models.PositiveIntegerField(help_text='Orden de secuencia (1-7)', unique=True)),
                ('estimated_time_minutes', models.PositiveIntegerField(default=30, help_text='Tiempo estimado en minutos')),
                ('requires_approval', models.BooleanField(default=True, help_text='Requiere aprobación de usuario')),
                ('is_active', models.BooleanField(default=True, help_text='Operación activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='ProcessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el proceso')),
                ('quality_check_passed', models.BooleanField(default=False, help_text='Control de calidad aprobado')),
                ('rejection_reason', models.TextField(blank=True, help_text='Razón del rechazo (se crea defecto automáticamente)')),
                ('defect_type', models.CharField(blank=True, help_text='Tipo de defecto cuando se rechaza', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_operator', models.ForeignKey(blank=True, help_text='Operador actualmente asignado a esta operación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operations', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.operation')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_operations', to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_records', to='serials.serialnumber')),
            ],
            options={
                'verbose_name': 'Registro de Proceso',
                'verbose_name_plural': 'Registros de Proceso',
                'ordering': ['serial_number', 'operation__sequence_number'],
                'unique_together': {('serial_number', 'operation')},
            },
        ),
    ]
